### PR TITLE
Add test files from uchardet

### PR DESCRIPTION
**Pull request by rstm-sf**
Add some files from [uchardet](https://gitlab.freedesktop.org/uchardet/uchardet/tree/master/test) for batch test.

<details>
  <summary>Others, I either did not understand whether it was worth adding, or they could not be added (such are highlighted in bold)</summary>

bd - ??? cirilic
ce - __mac-centraleurope = null (not encoding in .net?)__
da - __iso-8859-1 = But was:  "ISO-8859-15__"; windows-1252 = ???
de - iso-8859-1, windows-1252 = ??? we
en - __why ascii???__
es - ???
et - iso-8859-15, windows-1252 = ???
fi - ???
fr - iso-8859-1, iso-8859-15, windows-1252 = ???
ga - ???
he - ???
hr - __iso-8859-16 = null__; other ???
hu - ???
it - ???
ja - __utf-16le = fail__;  other ???
ko - ??? (but utf-16le)
lt - __iso-8859-10 = null__; other ???
lv - ???
mt - ???
pl - ???
pt - ???
ro - ???
ru - ??? (but iso-8859-5)
sk - ???
sl - ???
sv - ???
tr - iso-8859-3 ???
vi - __viscii = null__
zh - ???

</details>

### CODE REVIEW

**Comment by rstm-sf** [comment]
@304NotModified, how is it going?

**Comment by 304NotModified** [comment]
Hey! Thanks for the reminder. Will try to look at this soon

**Comment by 304NotModified** [comment]
> Others, I either did not understand whether it was worth adding, or they could not be added (such are highlighted in bold)

We need to figure this out before merging this, isn't?

**Comment by rstm-sf** [comment]
> iso-8859-1, iso-8859-10, iso-8859-16, viscii

I did not find [here](https://github.com/dotnet/corefx/blob/cf28b7896a762f71c990a5896a160a4138d833c9/src/System.Text.Encoding.CodePages/src/System/Text/EncodingTable.Data.cs) a definition of such encoding

> ce - mac-centraleurope = null (not encoding in .net?)

I guess that will be resolved by correction on the _x-mac-ce_

> da - iso-8859-1 = But was: "ISO-8859-15"

Sorry, but I don’t remember why I singled out. I think that it will recover quickly if you start over again.

> en - why ascii???

Good question. [The text](https://gitlab.freedesktop.org/uchardet/uchardet/blob/master/test/en/ascii.txt) of the test file is given for thought.

> ja - utf-16le = fail

Create issue  #72

Probably the previous ones should also create issues.

**Comment by rstm-sf** [comment]
Maybe the following links will help us somehow:
- [What is the exact difference between Windows-1252(1/3/4) and ISO-8859-1?](https://stackoverflow.com/q/19109899)
- [Open Specifications (msdn) / 2.1 Normative Variations](https://docs.microsoft.com/en-us/openspecs/ie_standards/ms-iso8859/08043577-fbe9-407b-bcff-8a280b82072a)

**Comment by rstm-sf** [comment]
hmm, but [there is _iso-8859-1_](https://docs.microsoft.com/en-us/windows/win32/intl/code-page-identifiers)

**Comment by rstm-sf** [comment]
> iso-8859-1

I overlooked something and in fact [it exists by default](https://docs.microsoft.com/en-us/dotnet/api/system.text.codepagesencodingprovider).

Then

> da - iso-8859-1 = But was: "ISO-8859-15"

Sounds like a mistake.

**Comment by rstm-sf** [comment]
> Probably the previous ones should also create issues.

Done: #75, #76, #77

**Comment by 304NotModified** [comment]
Thanks! Merge this as I think it a nice improvement :)

**Pull request merged**
