### PR TITLE
Generalization_and_added_languages

### PR DESCRIPTION
**Pull request by msdobrescu**
The first commit, please review.

### CODE REVIEW

**Comment by 304NotModified** [comment]
any idea why this test is failing?


```
Starting test execution, please wait...
Failed   TestFile(iso-8859-7: greek.txt)
Error Message:
   Charset detection failed for C:\utfUnknown\tests\Data\iso-8859-7\greek.txt. Expected: iso-8859-7, detected: windows-1253 (73.84949% confidence)
  Expected string length 10 but was 12. Strings differ at index 0.
  Expected: "iso-8859-7", ignoring case
  But was:  "windows-1253"
  -----------^
Stack Trace:

```

**Comment by msdobrescu** [comment]
Does it work on your computer, locally?

**Comment by 304NotModified** [comment]
I will check

**Comment by msdobrescu** [comment]
It seems to have an issue related to encoding name length, or is it a coincidence? "iso-8859-7" has 10, "windows-1253" has 12.

**Comment by msdobrescu** [comment]
So StringAssert throws an exception. But the test fails only on git. There might be something not committed that makes it to identify it in the other Greek encoding.

**Comment by msdobrescu** [comment]
Could it be some Windows vs Linux line ending issue?

**Comment by 304NotModified** [comment]
it's succeeds locally indeed. 

> Could it be some Windows vs Linux line ending issue?

Yeah also think off, but then there is a bug I guess

**Comment by msdobrescu** [comment]
Did it pass before? At what score?
I could update the Greek tables.

**Comment by 304NotModified** [comment]
> Did it pass before? At what score?

yes,



> I could update the Greek tables.

Don't know, we could log it maybe

**Comment by 304NotModified** [comment]
> Don't know, we could log it maybe

see (branched from master) https://ci.appveyor.com/api/buildjobs/mwvhc00t48u0ydl5/artifacts/tests%2Ftest-diag.log

(logged by: https://github.com/CharsetDetector/UTF-unknown/commit/3e21086051c8ea195a9feeaeb2722a13bec5e346)

**Comment by msdobrescu** [comment]
OK, then?

**Comment by 304NotModified** [comment]
Maybe we could test it locally with different line endings

**Comment by msdobrescu** [comment]
Or let's add a 0D at the end, I have downloaded it and see it's 0A only. Or remove it completely (let's add both versions in the directory) and see what happens.

**Comment by 304NotModified** [comment]
PS: You could use VS code for change the line endings. (bottom right)

**Comment by msdobrescu** [comment]
I know this is unreliable, but ... looking here: https://en.wikipedia.org/wiki/ISO/IEC_8859-7 and here: https://en.wikipedia.org/wiki/Windows-1253, what do you understand regarding CR and LF? Is it missing from ISO-8859-7?

**Comment by 304NotModified** [comment]
AFAIK ascii (0-127) is always encoded the same way , so that's always with LF (10 dec) and CR (13 dec)

have to agree that the table on https://en.wikipedia.org/wiki/ISO/IEC_8859-7 is confusing

**Comment by msdobrescu** [comment]
I think it is not a new line issue.

**Comment by msdobrescu** [comment]
Basically, there are two identical files for Greek. One put in iso-8859-7 folder, one in windows-1253 folder.
Obviously, they can't be detected as both.
Weird fact: locally, the windows-1253 file is detected as iso-8859-7, on github the iso-8859-7 file is detected as windows-1253. Must be some OS difference after all, I have Windows here, Linux on github, probably.
Could also be the reason that is run as .net Core on github and .net 4.5.1 locally.

**Comment by 304NotModified** [comment]
> Basically, there are two identical files for Greek. One put in iso-8859-7 folder, one in windows-1253 folder.
> Obviously, they can't be detected as both.
> Weird fact: locally, the windows-1253 file is detected as iso-8859-7, on github the iso-8859-7 file is detected as windows-1253. Must be some OS difference after all, I have Windows here, Linux on github, probably.
> Could also be the reason that is run as .net Core on github and .net 4.5.1 locally.

AppVeyor is also Windows ;)

**Comment by msdobrescu** [comment]
What else can we do?

**Comment by 304NotModified** [comment]
> Basically, there are two identical files for Greek.

There should be differences in bytes? 

PS: releasing 1.0 RTM now (and this will be 1.1 probably)

**Comment by msdobrescu** [comment]
I think there must be different chars (between the two encodings) in order to identify them as one or another, right? Otherwise, should fallback to the "smallest" one, I think.

**Comment by 304NotModified** [comment]
LOL the folder is also "windows-1253/not_working - reported as ISO 8859-7"

**Comment by msdobrescu** [comment]
I've thought you created it and moved it there to forcibly pass the tests.
Is it very likely that would work if we update the new tables.
Anyway, we could add and see.

Another thing I don't like is the organization. of the classes. uchardet has classes that contain all the tables for a language. It's practical, because there are one model table and potentially several char matching tables..

**Comment by msdobrescu** [comment]
I'm absolutely totally newbie with AppVeyor, but either it dies not the tests, either all pass... It works in my repo. Can you check?

**Comment by msdobrescu** [comment]
Hi, how can I access the log?

**Comment by msdobrescu** [comment]
Hi, I have added all my changes here, including many aggressive logging changes due to the fact I use a different Visual Studio, 2017, that saves unit testing files in other path since yesterday... some update?
I see both logs identical pn server and locally, but the logs are telling a different story... I keep looking.

**Comment by msdobrescu** [comment]
There is one thing it comes in mind, the error propagation. For some reason, a float is different on the server.

**Comment by msdobrescu** [comment]
Why do I see ISO chosen in the log, but ISO test fails as WIN?

**Comment by msdobrescu** [comment]
I don't know what to say, I start thinking there is a bug in AppVeyor.

**Comment by msdobrescu** [comment]
Hi, when I have added some debug string to get the charset decision order, it passed for the iso-8859-7 Greek file. I can't explain why.

**Comment by msdobrescu** [comment]
Hi, @304NotModified , are you still with me?
I have done a mess in order to diagnose the tests issues.
I would clean the code now.

**Comment by 304NotModified** [comment]
> Hi, @304NotModified , are you still with me?
> I have done a mess in order to diagnose the tests issues.
> I would clean the code now.

yes, but kinda busy with a new NLog release. (docs and other boring stuff...)

**Pull request closed without merging**
