### PR TITLE
Automatic code arrangement

### PR DESCRIPTION
**Pull request by adimosh**
Removed a lot of useless whitespace, unused usings, attempted to create a usable editorconfig file.

### CODE REVIEW

**Comment by rstm-sf** [comment]
Relying only on Visual Studio formatting is not really the right solution, as Rider/Resharper has different settings (broader?) and does not support all the formatting that is specified in the .editorconfig from the Studio. Perhaps a good idea would be to look towards the [dotnet-format](https://github.com/dotnet/format)

**Comment by adimosh** [comment]
While that may be true, the current state of the code does not implement anything, and the code is full of unused whitespace. While I can definitely use R# to make something better, I have seen no indication that the project collaborators intended that to be the case.

**Comment by adimosh** [comment]
@rstm-sf - would me removing the editorconfig file from this PR make it more merge-worthy? It's basically just code cleanup and wants to be nothing more.

**Comment by 304NotModified** [comment]
I think this is a nice improvement:)

Haven't checked it indepth yet

**Review by 304NotModified — APPROVED** [review]

**Comment by 304NotModified** [comment]
I think this is a nice improvement. Checked that this only a whitespace changes (and also removed some unneeded imports and fixed comment typos, so nice)

**Pull request merged**
