### PR TITLE
Refactor to get encoding by string name

### PR DESCRIPTION
**Pull request by rstm-sf**
Hello!

Refactor to get encoding by string name

_What for?_

To enable the library user to get the encoding from his [`EncodingProvider`](https://docs.microsoft.com/ru-ru/dotnet/api/system.text.encodingprovider). But it will be redundant if the user referenced to `System.Text.Encoding.CodePages` and if he does not need this library.

And unnecessary target assembly present redundant assembly: `netcoreapp2.0` (replace by `netstandard 2.0`)

### CODE REVIEW

**Comment by rstm-sf** [comment]
In general, the problem associated with the `System.Text.Encoding` class can be solved by using an extension in a separate project (removing the property `DetectionDetail.Encoding` responsible for this from the main project). So we will maintain compatibility with the old API and free ourselves from the dependency in the form of `System.Text.Encoding.CodePages`. Because in modern realities, it looks redundant

**Comment by rstm-sf** [comment]
We need a target for `net452`?

**Comment by rstm-sf** [comment]
And we need the *.snk?

https://github.com/CharsetDetector/UTF-unknown/blob/303f0243024bd24fc1733dbcc47468ddf0eebf1e/src/UTF-unknown.csproj#L65

**Comment by rstm-sf** [comment]
> 
> 
> We need a target for `net452`?

@304NotModified, hello!

It seems superfluous to test for `net452` and `net472` -- need to leave one thing

`netcoreapp2.0` for .NET Standard (maybe something different from Core 2.0?)

`netcoreapp3.0` for .NET Core 3.0

**Comment by 304NotModified** [comment]
> It seems superfluous to test for `net452` and `net472` -- need to leave one thing

I think it's also not needed to test both.

**Comment by 304NotModified** [comment]
:+1: thanks!

**Pull request merged**
