### PR TITLE
Enable nullable reference types for main source code

### PR DESCRIPTION
**Pull request by rstm-sf**
Hello!

Enable nullable reference types for main source code. It seems to be without breaking changes

### CODE REVIEW

**Comment by 304NotModified** [comment]
@rstm-sf do you know if this is a (binary) breaking change?

**Comment by rstm-sf** [comment]
Nullable Reference Types affect only the compiler, and if support is disabled, then no effect will be provided
- This is not binary breaking change
- This is not source breaking change
- This is a source breaking change if the relevant compiler warnings are marked as `WarningsAsErrors`

**Comment by rstm-sf** [comment]
probably it is better to do it with [src/Core](https://github.com/CharsetDetector/UTF-unknown/tree/master/src/Core) as `internal` modification

**Comment by 304NotModified** [comment]
> Nullable Reference Types affect only the compiler, and if support is disabled, then no effect will be provided
> 
> * This is not binary breaking change
> * This is not source breaking change
> * This is a source breaking change if the relevant compiler warnings are marked as `WarningsAsErrors`

Well I'm not sure if that's so simple. See https://docs.microsoft.com/en-us/dotnet/csharp/nullable-migration-strategies

> However, for public libraries, or libraries with large user bases, you may prefer not introducing any API signature changes.

**Comment by rstm-sf** [comment]
Ok, let's take look at this in a separate issue #121. And I'll just close this PR, as it became a topic for discussion

**Pull request closed without merging**
