### PR TITLE
Fix todo: ISO-2022-CN is x-cp50227 in .NET

### PR DESCRIPTION
**Pull request by rstm-sf**
Resolve task  #78
> Not supported iso-2022-ch? Maybe fix to x-cp50227?

Sorry, but I could not find an example.

### CODE REVIEW

**Comment by rstm-sf** [comment]
I'm confused, I’ll fix it now

**Comment by 304NotModified** [comment]
so 50229  is unsupported but also iso-2022-ch?  But  x-cp50227 is supported?

**Comment by rstm-sf** [comment]
Yes, I somehow wrote with a double meaning.

If you go to get the encoding by identifier `50229`, then you will get an exception in .NET Framework:
```
System.NotSupportedException : The ISO-2022-CN Encoding (Code page 50229) is not supported.
```
It is possible that it was or was supposed to be `ISO-2022-CN-EXT` encoding.

`x-cp50227` has the identifier `50227` and is `ISO-2022-CN` encoding according to the [doc/win32](https://docs.microsoft.com/en-us/windows/win32/intl/code-page-identifiers).

P.S. Now I need to make 2 edits

**Comment by rstm-sf** [comment]
> P.S. Now I need to make 2 edits

Done

**Comment by 304NotModified** [comment]
Thanks!

**Pull request merged**
